// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cli

import (
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

// InitializeRootCmd uses Wire to inject dependencies and construct the root command.
func InitializeRootCmd() *cobra.Command {
	command := NewRootCommand()
	return command
}
