package llm

import (
	"context"
	"encoding/json"
	"time"
)

// PartType identifies the structural intent of a Message Part.
type PartType string

const (
	TypeText           PartType = "text"
	TypeReasoning      PartType = "reasoning"
	TypeImage          PartType = "image"
	TypeToolCall       PartType = "tool_call"
	TypeToolDefinition PartType = "tool_definition"
	TypeToolResult       PartType = "tool_result"
	TypeTransitionSignal PartType = "transition_signal"
	TypeTelemetry        PartType = "telemetry"
)

// Part defines an abstract section of an LLM generation.
// The Type() method allows downstream adapters (like Slack) to branch UI logic
// based on the part's intent, decoupled from how the part physically marshals itself.
type Part interface {
	Type() PartType
}

// TextPart represents standard conversational text.
type TextPart string

func (t TextPart) Type() PartType { return TypeText }

// MarshalText conforms strictly to the standard Go encoding interfaces.
func (t TextPart) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// ReasoningPart represents chain-of-thought or provider-supplied reasoning.
type ReasoningPart string

func (r ReasoningPart) Type() PartType { return TypeReasoning }

// MarshalText conforms strictly to the standard Go encoding interfaces.
func (r ReasoningPart) MarshalText() ([]byte, error) {
	return []byte(r), nil
}

// ImagePart represents image data for multimodal LLMs.
type ImagePart struct {
	MIMEType string
	Data     []byte
	URL      string
}

func (i ImagePart) Type() PartType { return TypeImage }

// ToolRequestPart carries arguments that evaluate downstream.
type ToolRequestPart struct {
	ToolID string
	Name   string
	Args   map[string]interface{}
}

func (t ToolRequestPart) Type() PartType { return TypeToolCall }

// MarshalJSON conforms strictly to standard Go encoding libraries, offloading
// the burden of formatting to standard types.
func (t ToolRequestPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Tool string                 `json:"tool"`
		Args map[string]interface{} `json:"args"`
	}{
		Tool: t.Name,
		Args: t.Args,
	})
}

// ToolDefinitionPart implements Part, allowing tool schemas to be passed dynamically
// inside the Message structure as structural "specialized context".
type ToolDefinitionPart struct {
	Name        string
	Description string
	Parameters  json.RawMessage // e.g. JSON Schema
}

func (t ToolDefinitionPart) Type() PartType { return TypeToolDefinition }

// ToolResultPart carries the output of a locally or remotely executed tool.
type ToolResultPart struct {
	ToolID  string      // Maps back to the original request (if provider supports it)
	Name    string      // Which tool this answers
	Result  interface{} // Struct/Map that marshals cleanly to JSON
	IsError bool        // Indicates if the tool threw a business-logic error
}

func (t ToolResultPart) Type() PartType { return TypeToolResult }

// TransitionSignalPart represents an internal signal generated by a transition tool.
// It instructs the adapter Engine to break the recursive turn loop and yield
// to the context loop to swap the active workflow mode.
type TransitionSignalPart struct {
	TargetMode string
	Message    string
}

func (t TransitionSignalPart) Type() PartType { return TypeTransitionSignal }

// TelemetryPart represents provider execution metrics (token usage, latency).
type TelemetryPart struct {
	InputTokens     int
	OutputTokens    int
	ReasoningTokens int
	Duration        time.Duration
}

func (t TelemetryPart) Type() PartType { return TypeTelemetry }

type Volatility int8

const (
	VolatilityStatic Volatility = 0  // Never changes (e.g. System Prompt, Guardrails)
	VolatilityLow    Volatility = 3  // Rarely changes (e.g. Static agent instructions)
	VolatilityMedium Volatility = 5  // Occasional (e.g. Contextual RAG data)
	VolatilityHigh   Volatility = 10 // Turn-by-turn (e.g. Conversation History, Tool definitions)
)

// Identity represents the exact source and nature of a message.
type Identity struct {
	Role string // e.g., "user", "assistant", "system", "tool"
	Name string // The name of the specific tool or agent interacting
}

// Message is the upgraded payload structure representing a completely isolated event.
type Message struct {
	ID         string
	SessionID  string
	Identity   Identity
	Parts      []Part // Flexible payload list instead of a rigid string
	Attributes map[string]string
	Volatility Volatility
}

// Text extracts all TypeText parts and joins them into a single string.
func (m Message) Text() string {
	var text string
	for _, p := range m.Parts {
		if tp, ok := p.(TextPart); ok {
			text += string(tp)
		}
	}
	return text
}

// Receiver yields incoming messages over a channel. It acts as an asynchronous producer.
// The provided context should control the lifetime of the receiver.
type Receiver interface {
	Receive(ctx context.Context) (<-chan Message, error)
}

// Sender writes output messages back to a transport layer.
type Sender interface {
	Send(ctx context.Context, msg Message) error
}
